title: Blaze Pollard
email: blazepollard@gmail.com
url: ""
author: Blaze Pollard
twitter_username: blazepollard
github_username:  blazepollard

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _scss
  style: :compressed
